FROM python:3.6.6-slim

ENV PYTHONUNBUFFERED 1

RUN \
    apt-get update && \
    apt-get install build-essential curl -y --no-install-recommends

COPY requirements.txt .
COPY requirements-test.txt .

RUN \
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install -r requirements-test.txt
