{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-lompret-centre-splendide-plain-pied-individuel-sur-750-m-de-terrain,9303", "title": "Lompret Centre \" splendide plain pied individuel\" sur 750 m\u00b2 de terrain", "description": "", "sku": "LA9302", "city": "lompret", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9303/photo-8-g.jpg"], "price": 445000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-wasquehal-sart-a-vendre-proximite-lille,9304", "title": "Maison Wasquehal Sart \u00e0 vendre (Proximit\u00e9 Lille)", "description": "", "sku": "WA9303", "city": "wasquehal", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9304/photo-2-g.jpg"], "is_dirty": true}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-mouvaux-st-germain-maison,9305", "title": "Mouvaux St Germain, maison", "description": "", "sku": "MO9304", "city": "mouvaux", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9305/photo-1-g.jpg"], "price": 263000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-campagne-de-leers-rare-sur-le-secteur,9286", "title": "Campagne de LEERS - Rare sur le secteur", "description": "", "sku": "HE9285", "city": "leers", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9286/photo-11-g.jpg"], "price": 830000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-lambersart-conquerants-maison-3-chambres-sejour-de-43-m2-avec-garage-et-jardin,9287", "title": "Lambersart \"Conquerants\" maison 3 chambres, s\u00e9jour de 43 m2 avec garage et jardin", "description": "", "sku": "LA9286", "city": "lambersart", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9287/photo-1-g.jpg"], "price": 249000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-lesquin-a-vendre,9288", "title": "Maison Lesquin \u00e0 vendre", "description": "", "sku": "VI9287", "city": "lesquin", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9288/photo-1-g.jpg"], "price": 225000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-hem-residentiel-la-chapelle-madame,9271", "title": "HEM RESIDENTIEL LA CHAPELLE MADAME", "description": "", "sku": "HE9270", "city": "hem", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9271/photo-1-g.jpg"], "price": 440000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-a-vendre,9239", "title": "Maison Villeneuve d'ascq \u00e0 vendre", "description": "", "sku": "VI9238", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9239/photo-3-g.jpg"], "price": 335000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-ascq-a-vendre,9161", "title": "Maison Villeneuve d'Ascq (Ascq) \u00e0 vendre", "description": "", "sku": "VI9160", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9161/photo-4-g.jpg"], "price": 269000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-jolie-maison-flamande-a-proximite-immediate-de-seclin,9049", "title": "Jolie maison flamande \u00e0 proximit\u00e9 imm\u00e9diate de Seclin", "description": "", "sku": "PH9048", "city": "attiches", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9049/photo-6-g.jpg"], "price": 219000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-semi-individuelle-proximite-phalempin,8651", "title": "Maison semi individuelle Proximit\u00e9 Phalempin", "description": "", "sku": "PH8650", "city": "wahagnies", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8651/photo-1-g.jpg"], "price": 198000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-10-minutes-de-villeneuve-dascq,7628", "title": "10 minutes de Villeneuve d'Ascq", "description": "", "sku": "HE21", "city": "toufflers", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/7628/photo-1-g.jpg"], "price": 1300.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-wasquehal-saint-clement-a-vendre-proximite-lille,7944", "title": "Maison Wasquehal Saint Cl\u00e9ment \u00e0 vendre (Proximit\u00e9 Lille)", "description": "", "sku": "WA4057", "city": "wasquehal", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/7944/photo-1-g.jpg"], "price": 309000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-plain-pied-individuel-proximite-phalempin,8229", "title": "Plain pied individuel proximit\u00e9 Phalempin", "description": "", "sku": "PH8228", "city": "phalempin", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8229/photo-5-g.jpg"], "price": 369500.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-roubaix-limite-croix-proximite-lille,8295", "title": "Maison Roubaix Limite Croix (Proximit\u00e9 Lille)", "description": "", "sku": "WA4056", "city": "roubaix", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8295/photo-1-g.jpg"], "price": 149000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-a-proximite-de-hem-et-de-villeneuve-dascq,8300", "title": "A proximit\u00e9 de HEM et de VILLENEUVE D'ASCQ", "description": "", "sku": "HE8299", "city": "sailly-lez-lannoy", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8300/photo-1-g.jpg"], "price": 890000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-terrain-a-batir-situe-a-thumeries,8308", "title": "Terrain \u00e0 b\u00e2tir situ\u00e9 \u00e0 Thumeries", "description": "", "sku": "PH8307", "city": "thumeries", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8308/photo-1-g.jpg"], "price": 82000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-annappes-a-vendre,8672", "title": "Maison Villeneuve d'Ascq (Annappes) \u00e0 vendre", "description": "", "sku": "VI8671", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8672/photo-1-g.jpg"], "price": 209000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-projet-de-renovation-haut-de-gamme-dans-secteur-canon-dor,8711", "title": "Projet de r\u00e9novation haut de gamme dans secteur Canon d'Or", "description": "", "sku": "LA8710", "city": "lambersart", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8711/photo-1-g.jpg"], "is_dirty": true}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-sainghin-en-melantois-a-vendre,8731", "title": "Maison Sainghin en M\u00e9lantois \u00e0 vendre", "description": "", "sku": "BA8730", "city": "sainghin-en-m\u00e9lantois", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8731/photo-3-g.jpg"], "is_dirty": true}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-hem-bourg,8743", "title": "HEM \"Bourg\"", "description": "", "sku": "HE8742", "city": "hem", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8743/photo-4-g.jpg"], "price": 179000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-wattrelos-centre,8889", "title": "WATTRELOS CENTRE", "description": "", "sku": "HE8888", "city": "wattrelos", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8889/photo-5-g.jpg"], "price": 138000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-magnifique-maison-bourgeoise-phalempin-centre,8801", "title": "Magnifique maison Bourgeoise PHALEMPIN centre", "description": "", "sku": "PH8800", "city": "phalempin", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8801/photo-2-g.jpg"], "price": 399000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-deulemont-maison-flamande-individuelle-a-vendre-proche-lille,8925", "title": "De\u00fblemont - Maison flamande individuelle \u00e0 vendre (proche Lille)", "description": "", "sku": "P\u00c98924", "city": "de\u00fblemont", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8925/photo-8-g.jpg"], "price": 388000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-superbe-maison-individuelle-a-thumeries,8953", "title": "Superbe maison individuelle \u00e0 Thumeries", "description": "", "sku": "PH8952", "city": "thumeries", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8953/photo-11-g.jpg"], "price": 599000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-verlinghem-exceptionnel-maison-contemporaine-de-106m-avec-parkings-prives,8975", "title": "Verlinghem Exceptionnel ! Maison contemporaine de 106m\u00b2 avec parkings priv\u00e9s.", "description": "", "sku": ".LA8974.", "city": "verlinghem", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8975/photo-1-g.jpg"], "price": 285000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-perenchies-maison-individuelle-a-vendre-proche-lille,8974", "title": "P\u00e9renchies - Maison individuelle \u00e0 vendre (proche Lille)", "description": "", "sku": "P\u00c98973", "city": "p\u00e9renchies", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/8974/photo-4-g.jpg"], "price": 347000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-proximite-lesquin-a-vendre,9012", "title": "Maison proximit\u00e9 Lesquin \u00e0 vendre", "description": "", "sku": "LE9011", "city": "avelin", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9012/photo-3-g.jpg"], "price": 351000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-superbe-individuelle-demeures-du-nord-a-thumeries,9063", "title": "Superbe Individuelle Demeures du Nord \u00e0 Thumeries", "description": "", "sku": "PH9062", "city": "phalempin", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9063/photo-1-g.jpg"], "price": 410000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-grande-maison-renovee-moncheaux,9074", "title": "Grande Maison r\u00e9nov\u00e9e MONCHEAUX", "description": "", "sku": "PH9073", "city": "thumeries", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9074/photo-1-g.jpg"], "price": 382000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-flers-chateau-a-vendre,9075", "title": "Maison Villeneuve d'ascq (Flers Ch\u00e2teau) \u00e0 vendre", "description": "", "sku": "VI9074", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9075/photo-10-g.jpg"], "price": 252000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-hem-saint-corneille,9081", "title": "HEM Saint Corneille", "description": "", "sku": "HE9080", "city": "hem", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9081/photo-6-g.jpg"], "price": 249000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-lambersart-proche-metro-jolie-maison-avec-jardin-sud-avec-parking-moto-et-velo,9101", "title": "Lambersart \" proche M\u00e9tro\" jolie maison avec jardin sud avec parking moto et v\u00e9lo.", "description": "", "sku": "LA9100", "city": "lambersart", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9101/photo-7-g.jpg"], "price": 159000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-hem,9108", "title": "HEM", "description": "", "sku": "HE9107", "city": "hem", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9108/photo-2-g.jpg"], "price": 195000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-hem-proximite-avenue-motte-et-avenue-gustave-delory,9170", "title": "HEM - Proximit\u00e9 Avenue Motte et Avenue Gustave Delory", "description": "", "sku": "HE9169", "city": "hem", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9170/photo-4-g.jpg"], "price": 210000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-individuelle-renovee-a-mons-en-pevele,9186", "title": "Individuelle r\u00e9nov\u00e9e \u00e0 Mons en P\u00e9v\u00e8le", "description": "", "sku": "PH9185", "city": "mons-en-p\u00e9v\u00e8le", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9186/photo-2-g.jpg"], "price": 319000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-perenchies-maison-1930-avec-jardin-a-vendre-proche-lille,9189", "title": "P\u00e9renchies - Maison 1930 avec jardin \u00e0 vendre (proche Lille)", "description": "", "sku": ".P\u00c99188.", "city": "p\u00e9renchies", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9189/photo-2-g.jpg"], "price": 179000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-baisieux-a-vendre,9225", "title": "Maison Baisieux \u00e0 vendre", "description": "", "sku": "BA9224", "city": "baisieux", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9225/photo-1-g.jpg"], "price": 198000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-willems-a-vendre,9229", "title": "Maison Willems \u00e0 vendre", "description": "", "sku": "BA9228", "city": "willems", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9229/photo-8-g.jpg"], "price": 399000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-neuve-situee-a-merignies,9245", "title": "Maison neuve situ\u00e9e \u00e0 M\u00e9rignies", "description": "", "sku": "PH9244", "city": "m\u00e9rignies", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9245/photo-1-g.jpg"], "price": 310000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-neuve-situee-a-merignies,9246", "title": "Maison neuve situ\u00e9e \u00e0 M\u00e9rignies", "description": "", "sku": "PH9245", "city": "m\u00e9rignies", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9246/photo-1-g.jpg"], "price": 307500.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-neuve-situee-a-merignies,9247", "title": "Maison neuve situ\u00e9e \u00e0 M\u00e9rignies", "description": "", "sku": "PH9246", "city": "m\u00e9rignies", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9247/photo-3-g.jpg"], "price": 315000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-ascq-a-vendre,9248", "title": "Maison Villeneuve d'Ascq (Ascq) \u00e0 vendre", "description": "", "sku": "VI9247", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9248/photo-8-g.jpg"], "price": 229000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-lambersart-verghelles-maison-avec-garage-attenant,9258", "title": "Lambersart \"Verghelles\" Maison avec garage attenant", "description": "", "sku": "LA9257", "city": "lambersart", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9258/photo-8-g.jpg"], "price": 247000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-flers-a-vendre,9261", "title": "Maison Villeneuve d'Ascq (Flers) \u00e0 vendre", "description": "", "sku": "VI9260", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9261/photo-3-g.jpg"], "price": 194000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-lesquin-a-vendre,9272", "title": "Maison Lesquin \u00e0 vendre", "description": "", "sku": "LE9271", "city": "lesquin", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9272/photo-1-g.jpg"], "price": 210000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-lesquin-a-vendre,9273", "title": "Maison Lesquin \u00e0 vendre", "description": "", "sku": "LE9272", "city": "lesquin", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9273/photo-1-g.jpg"], "price": 189000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-magnifique-bourgeoise-pleine-de-charme-a-renover-sur-le-canon-dor-exclusivite-,9274", "title": "Magnifique Bourgeoise pleine de charme \u00e0 r\u00e9nover sur le Canon d'or. Exclusivit\u00e9 !", "description": "", "sku": "LA9273", "city": "lambersart", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9274/photo-11-g.jpg"], "price": 498000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-flers-bourg-a-vendre,9277", "title": "Maison Villeneuve d'Ascq (Flers Bourg) \u00e0 vendre", "description": "", "sku": "VI9276", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9277/photo-1-g.jpg"], "price": 231000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-ascq-a-vendre,9279", "title": "Maison Villeneuve d'Ascq (Ascq) \u00e0 vendre", "description": "", "sku": "VI9278", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9279/photo-1-g.jpg"], "price": 278000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-hem-jardin-des-perspectives,9284", "title": "HEM \"Jardin des perspectives\"", "description": "", "sku": "HE9282", "city": "hem", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9284/photo-1-g.jpg"], "price": 267500.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-frelinghien-maison-individuelle-dans-clos-prive-proximite-lille,9285", "title": "Frelinghien - Maison individuelle dans clos priv\u00e9 (proximit\u00e9 Lille)", "description": "", "sku": "P\u00c99284", "city": "frelinghien", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9285/photo-2-g.jpg"], "price": 403000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-lambersart-canon-dor-maison-1930-avec-grand-garage-4-chambres-2-salles-de-bain,9290", "title": "Lambersart\" Canon d'or \" Maison 1930 avec grand garage\" 4 chambres 2 salles de bain", "description": "", "sku": "LA9289", "city": "lambersart", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9290/photo-2-g.jpg"], "price": 440000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-lesquin-a-vendre,9291", "title": "Maison Lesquin \u00e0 vendre", "description": "", "sku": "VI9290", "city": "lesquin", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9291/photo-1-g.jpg"], "price": 273000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-wasquehal-proximite-ecole-bilingue-maison,9292", "title": "Wasquehal, proximit\u00e9 \u00e9cole bilingue maison", "description": "", "sku": "MO9291", "city": "wasquehal", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9292/photo-2-g.jpg"], "price": 365000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-mouvaux-st-germain-maison,9293", "title": "Mouvaux St Germain, maison", "description": "", "sku": "MO9292", "city": "mouvaux", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9293/photo-3-g.jpg"], "price": 335000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-annappes-a-vendre,9295", "title": "Maison Villeneuve d'Ascq (Annappes) \u00e0 vendre", "description": "", "sku": "VI9294", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9295/photo-1-g.jpg"], "price": 239800.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-flers-chateau-a-vendre,9296", "title": "Maison Villeneuve d'Ascq (Flers Ch\u00e2teau) \u00e0 vendre", "description": "", "sku": "VI9295", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9296/photo-2-g.jpg"], "price": 315000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-toufflers,9299", "title": "TOUFFLERS", "description": "", "sku": "HE9297", "city": "toufflers", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9299/photo-1-g.jpg"], "price": 305000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-annappes-a-vendre,9301", "title": "Maison Villeneuve d'Ascq (Annappes) \u00e0 vendre", "description": "", "sku": "VI9300", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9301/photo-9-g.jpg"], "price": 619000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-a-vendre-peronne-en-melantois,9302", "title": "Maison a vendre Peronne en Melantois", "description": "", "sku": "BA9301", "city": "p\u00e9ronne-en-m\u00e9lantois", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9302/photo-4-g.jpg"], "price": 440000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-a-vendre-chereng,9307", "title": "Maison \u00e0 vendre Chereng", "description": "", "sku": "BA9306", "city": "ch\u00e9reng", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9307/photo-1-g.jpg"], "price": 215000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-flers-a-vendre,9308", "title": "Maison Villeneuve d'Ascq (Flers) \u00e0 vendre", "description": "", "sku": "VI9307", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9308/photo-4-g.jpg"], "price": 310000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-lambersart-canon-dor-1930-coup-de-coeur-4-chambres-2-salles-de-bains,9310", "title": "Lambersart \" Canon d'or \" 1930 coup de coeur 4 chambres 2 salles de bains", "description": "", "sku": "LA9309", "city": "lambersart", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9310/photo-6-g.jpg"], "price": 430000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-campagne-de-lambersart-superbe-plain-pied-individuel-sur-750-m-de-terrain,9313", "title": "Campagne de Lambersart \" Superbe plain pied individuel\" sur 750 m\u00b2 de terrain", "description": "", "sku": "LA9302", "city": "lambersart", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9313/photo-3-g.jpg"], "price": 445000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-residence-annappes-a-vendre,9316", "title": "Maison Villeneuve d'Ascq (R\u00e9sidence-Annappes) \u00e0 vendre", "description": "", "sku": "VI9315", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9316/photo-3-g.jpg"], "price": 225000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-lesquin-a-vendre,9317", "title": "Maison Lesquin \u00e0 vendre", "description": "", "sku": "VI9316", "city": "lesquin", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9317/photo-6-g.jpg"], "price": 169000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-plain-pied-villeneuve-dascq-chateau-a-vendre,9318", "title": "Maison Plain-pied Villeneuve d'Ascq (Ch\u00e2teau) \u00e0 vendre", "description": "", "sku": "VI9317", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9318/photo-8-g.jpg"], "price": 241000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-residence-annappes-a-vendre,9319", "title": "Maison Villeneuve d'Ascq (R\u00e9sidence-Annappes) \u00e0 vendre", "description": "", "sku": "VI9318", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9319/photo-2-g.jpg"], "price": 246000.0}
{"url": "https://www.avenue-immobilier-metropole.fr/bien-vente-maison-villeneuve-dascq-flers-a-vendre,9309", "title": "Maison Villeneuve d'Ascq (Flers) \u00e0 vendre", "description": "", "sku": "VI9308", "city": "villeneuve-d'ascq", "media": ["http://www.avenue-immobilier-metropole.fr/templates/bienPhoto/9309/photo-2-g.jpg"], "price": 332000.0}
